#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running lint-staged on staged files ..."

npx lint-staged

# # # ... instead of the following ...
# echo "🔍 Running pre-commit processes/checks ... linting, formatting, testing ..."
#
# npm run lint:fix
# npm run format
# npm run test
